apiVersion: v1
kind: Service
metadata:
  name: fibo-service
spec:
  selector:
    app: fibo
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibo-deploy
spec:
  selector:
    matchLabels:
      app: fibo
  replicas: 1
  template:
    metadata:
      labels:
        app: fibo
    spec:
      containers:
      - name: fibo
        image: rafal-pienkowski/fibo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /fib?n=1
            port: 8080
          initialDelaySeconds: 4
          timeoutSeconds: 5
          periodSeconds: 5
       
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: fibo-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibo-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 512Mi